### ISSUE TITLE
ImageLoader

### ISSUE THREAD

**Issue by yestianxu** [Hitomis/transferee#101]
能写个Picasso的ImageLoader么

**Comment by hyyaoming** [comment]
https://github.com/Hitomis/transferee/blob/master/Transferee/src/main/java/com/hitomi/tilibrary/loader/ImageLoader.java
自己实现这个接口就好了呀。

**Comment by hyyaoming** [comment]
> 能写个Picasso的ImageLoader么

https://github.com/Hitomis/transferee/blob/master/Transferee/src/main/java/com/hitomi/tilibrary/loader/ImageLoader.java
自己实现这个接口就好了呀。

**Comment by Hitomis** [comment]
[#102](https://github.com/Hitomis/transferee/issues/102) 新增了 GlideImageLoader ,还有这种需求的，请依葫芦画瓢。thx~

**Comment by yestianxu** [comment]
你这个接口完全是针对glide写的

**Comment by yestianxu** [comment]
ImageLoader接口我感觉对glide的针对性太强了，不是很好改成piassco的，并且我肯定是试过了才来说的，不是一句依葫芦画瓢就可以的。不过提不提供都没关系，我只是想杠一下，没想你会回复。

**Comment by Hitomis** [comment]
这个接口并不是对glide写的。我今天才接的glide 之前一直用的univsal。。。------------------ 原始邮件 ------------------
发件人: "yestianxu"<notifications@github.com>
发送时间: 2020年2月28日(星期五) 晚上6:51
收件人: "Hitomis/transferee"<transferee@noreply.github.com>;
抄送: "Vans Z"<196425254@qq.com>;"Comment"<comment@noreply.github.com>;
主题: Re: [Hitomis/transferee] ImageLoader (#101)



ImageLoader接口我感觉对glide的针对性太强了，不是很好改成piassco的，并且我肯定是试过了才来说的，不是一句依葫芦画瓢就可以的。不过提不提供都没关系，我只是想杠一下，没想你会回复。
 
&mdash;

**Comment by Hitomis** [comment]
@yestianxu Picasso 的所有接口我看过了一遍，几乎和 Glide 一模一样。我相信写个PicassoImageLoader也是完全 ok 的。

**Comment by Hitomis** [comment]
@yestianxu bro. 疫情在家。时间宽裕。已经实现了 PicassoImageLoader. 你拿去用吧

**Comment by yestianxu** [comment]
谢谢，我也是后来看到你更新了，所以把之前的说的删了。之前说的时候还不知道更新了。
