### ISSUE TITLE
The lib Universalimageloader has been Deprecated

### ISSUE THREAD

**Issue by KevinChang007** [Hitomis/transferee#102]
The lib has been deprecated several years, so we'd better replace it with new lib, such as Glide, Fresco and so on.
Thanks.

**Comment by Hitomis** [comment]
目前我新增了GlideImageLoader. 还有需求的同学可以实现 ImageLoader 接口去实现自己想要的图片加载器。实现起来没有那么杂。参考我提供的UniversalImageLoader 和 GlideImageLoader 实现起来应该不难。
感谢~

**Comment by Hitomis** [comment]
新增了 PicassoImageLoader
