### ISSUE TITLE
兄弟，你好，请问一下新版本大概多久会发布呢？

### ISSUE THREAD

**Issue by xiaozhiguang** [Hitomis/transferee#103]
RT

**Comment by Hitomis** [comment]
感谢你对这个项目的关注。目前还在开发一些厂商的 ImageLoader.和微调。不过不会修改 Transferee Module 的功能。所以你可以直接下载本项目。然后以 import module 的方式加入 Transferee。至于ImageLoader。你可以根据你的项目去导入即可
