### ISSUE TITLE
希望能提个这个库的混淆

### ISSUE THREAD

**Issue by Vince1221** [Hitomis/transferee#104]

**Comment by Hitomis** [comment]
不懂你的意思，这个库没有使用反射等需要防止混淆的代码。为什么要提混淆？

**Comment by Vince1221** [comment]
那好的，谢谢你




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Vans Z"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月2日(星期一) 中午11:22
收件人:&nbsp;"Hitomis/transferee"<transferee@noreply.github.com&gt;;
抄送:&nbsp;"张文"<948719044@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [Hitomis/transferee] 希望能提个这个库的混淆 (#104)




不懂你的意思，这个库没有使用反射等需要防止混淆的代码。为什么要提混淆？
