### ISSUE TITLE
【Gradle 依赖】Gradle 依赖库地址有更新吗？

### ISSUE THREAD

**Issue by ultravires** [Hitomis/transferee#105]
我准备用一下大大的插件，但是看到说 gradle 依赖失效，想问一下有没有更新。谢谢！

**Comment by Hitomis** [comment]
最近没有更新。直接下代码。import module 的方式使用吧。不好意思了

**Comment by ultravires** [comment]
谢谢回复！那我就直接审计源码了。

**Comment by ultravires** [comment]
对了  还有个问题想请教下楼主。请问一般图片展示效果是新建了视图还是改变了原来视图的大小。

比如我现在有一个发送的图片消息，我点击这个图片消息是改变了原来展示缩略图的大小还是在新的视图上展示的。 倍感打扰！

**Comment by Hitomis** [comment]
显示是使用 dialog，原理是拿到你点击图片的数据，然后新建一个视图层transferlayout ，在这个上面做的过渡改变。但是具体做伸缩效果的是TransferImage 。

**Comment by Hitomis** [comment]
@ultravires 可能你没有仔细看接口吧。绑定 RecyclerView 的时候你同时需要传一个 image 的 resId 。这个 id 就是用来精准捕获你的 Image 控件的。
关于你现在的需求模型如果是一个聊天界面，可以参考 #92 这个需求貌似和你一模一样
