### ISSUE TITLE
【提议】新增一个配置来兼容RecyclerView子布局的类型

### ISSUE THREAD

**Issue by ultravires** [Hitomis/transferee#106]
已成功将代码“复制 粘贴 Alt+Enter”引入到项目中。

提议背景如下：
1. 有一个即时消息项目，聊天界面采用了 RecyclerView 布局
2. 消息分多种消息类型；如：文本、图片、地理位置等。

遇到的问题：
通过代码审计发现此项目直接遍历了 RecyclerView 的所有子项而没有做组件类型判断，如果我的 RecyclerView 中是TextView 和 ImageView 穿插显示就会出现错误。

提议：
功能增强

PS: 额，本人学Android刚好才一个星期，提出的 issue 可能存在问题。如有问题请多多包涵！另外如果我的 issue 有问题最好给个建议。谢谢！

**Comment by Hitomis** [comment]
可能你没有仔细看接口吧。绑定 RecyclerView 的时候你同时需要传一个 image 的 resId 。这个 id 就是用来精准捕获你的 Image 控件的。
关于你现在的需求模型如果是一个聊天界面，可以参考 #92 这个需求貌似和你一模一样

**Comment by ultravires** [comment]
```java
List<String> imageUrlList = new ArrayList<String>();
                    imageUrlList.add("http://assets.sanphantom.com/avatar.jpg");

                    Transferee transferee = Transferee.getDefault(ChatActivity.this);
                    TransferConfig config = TransferConfig.build()
                            .setSourceImageList(imageUrlList) // 图片url集合
                            .setMissPlaceHolder(R.mipmap.default_img_failed) // 图片加载前的占位图
                            .setErrorPlaceHolder(R.mipmap.default_img_failed) // 图片加载错误后的占位图
                            .setProgressIndicator(new ProgressPieIndicator()) // 图片加载进度指示器
                            .setIndexIndicator(new NumberIndexIndicator()) // 图片数量索引指示器
                            .setImageLoader(GlideImageLoader.with(getApplicationContext())) // 设置图片加载器
                            .setJustLoadHitImage(true) // 是否只加载当前显示在屏幕中的的图片
                            .enableDragClose(true) // 开启拖拽关闭
                            .setOnLongClcikListener(new Transferee.OnTransfereeLongClickListener() {
                                @Override
                                public void onLongClick(ImageView imageView, String imageUri, int pos) {
                                    // TODO 长按图片进行保存
                                }
                            })
                            .bindRecyclerView(mRvChat, R.id.bivPic);
                    config.setNowThumbnailIndex(0);
                    transferee.apply(config).show();
```


代码里有写  `.bindRecyclerView(mRvChat, R.id.bivPic);` ；下面设置` nowThumbnailIndex ` 如果传当前 position 就会报错提示 _越界_，错误提示如下：

> Index bounded of index 13, but size is 1.

错误大致意思是，当前消息的索引是 13，但是你的图片集合大小为 1 。

**Comment by ultravires** [comment]
补充： 调试代码时  代码走到了这个位置 `Transferee.java`

```java
private void fillByRecyclerView(final List<ImageView> originImageList) {
        RecyclerView recyclerView = transConfig.getRecyclerView();
        int childCount = recyclerView.getChildCount();
        for (int i = 0; i < childCount; i++) {
            // TODO 兼容即时通讯项目处理
            ImageView originImage = ((ImageView) recyclerView.getChildAt(i)
                    .findViewById(transConfig.getImageId()));
            originImageList.add(originImage);
        }
        ...
}
```

**Comment by Hitomis** [comment]
这个错误和 #92 一样的。你仔细看看我的解答，应该能明白。

**Comment by ultravires** [comment]
好的，谢谢楼主。很抱歉用你的 issue 进行问题询问。我先研究研究！

```java
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.leadal.mobile, PID: 32119
    java.lang.NullPointerException: Attempt to invoke virtual method 'void android.view.View.getLocationInWindow(int[])' on a null object reference
        at com.leadal.im.tilibrary.transfer.TransferState.getViewLocation(TransferState.java:82)
        at com.leadal.im.tilibrary.transfer.TransferState.createTransferImage(TransferState.java:95)
        at com.leadal.im.tilibrary.transfer.LocalThumbState.createTransferIn(LocalThumbState.java:40)
        at com.leadal.im.tilibrary.transfer.TransferLayout.show(TransferLayout.java:272)
        at com.leadal.im.tilibrary.transfer.Transferee.onShow(Transferee.java:267)
        at android.app.Dialog$ListenersHandler.handleMessage(Dialog.java:1581)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:213)
        at android.app.ActivityThread.main(ActivityThread.java:8147)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1101)
```

**Comment by Hitomis** [comment]
这里我还是针对你的错误给你解释一下：其实就是你需要保证你的 originImageList 中的图片数量大于等于 recyclerView item 的数量就可以的。这个也很好理解：一般一个 item 肯定对应一个 imageView，那就需要一张图片展示。不会说你只给我一张图片，但是现在有13个item。那其他12个item 怎么处理。你没告诉我，那只能null pointer 勒

**Comment by ultravires** [comment]
嗯  其实我有做增加数据防止越界的测试。但最终的问题好像停留在上面的异常中(https://github.com/Hitomis/transferee/issues/106#issuecomment-597433971)。

我是这么分析的:

```java
for (int i = 0; i < childCount; i++) {
            // TODO 兼容即时通讯项目处理
            ImageView originImage = ((ImageView) recyclerView.getChildAt(i)
                    .findViewById(transConfig.getImageId()));
            originImageList.add(originImage);
        }
```

这段代码中 `recyclerView.getChildAt(i).findViewById(transConfig.getImageId()))` 存在该 child 为非 ImageId 的情况，然后会得到 `originImage`  为空，然后就会导致上面的异常。然后我加了一个判断解决了这个问题：

```java
for (int i = 0; i < childCount; i++) {
            ImageView originImage = ((ImageView) recyclerView.getChildAt(i)
                    .findViewById(transConfig.getImageId()));
            if (originImage == null) { // continue
                continue;
            }
            originImageList.add(originImage);
        }
```

**Comment by Hitomis** [comment]
你这个修改是可以的，其实只需要绑定单个imageview也可以达到你想要的效果。------------------ 原始邮件 ------------------
发件人: "ultravires"<notifications@github.com>
发送时间: 2020年3月11日(星期三) 中午12:32
收件人: "Hitomis/transferee"<transferee@noreply.github.com>;
抄送: "Vans Z"<196425254@qq.com>;"Comment"<comment@noreply.github.com>;
主题: Re: [Hitomis/transferee] 【提议】新增一个配置来兼容RecyclerView子布局的类型 (#106)



嗯  其实我有做增加数据防止越界的测试。但最终的问题好像停留在上面的异常中(https://github.com/Hitomis/transferee/issues/106#issuecomment-597433971)。
 
我是这么分析的:
 for (int i = 0; i < childCount; i++) {             // TODO 兼容即时通讯项目处理             ImageView originImage = ((ImageView) recyclerView.getChildAt(i)                     .findViewById(transConfig.getImageId()));             originImageList.add(originImage);         }
 
这段代码中 recyclerView.getChildAt(i).findViewById(transConfig.getImageId())) 存在该 child 为非 ImageId 的情况，然后会得到 originImage  为空，然后就会导致上面的异常。然后我加了一个判断解决了这个问题：
 for (int i = 0; i < childCount; i++) {             ImageView originImage = ((ImageView) recyclerView.getChildAt(i)                     .findViewById(transConfig.getImageId()));             if (originImage == null) { // continue                 continue;             }             originImageList.add(originImage);         }
 
&mdash;
