### ISSUE TITLE
RecyclerView 添加了Header,位移动画会错位

### ISSUE THREAD

**Issue by Vonnie0709** [Hitomis/transferee#112]
如题，
并且沉浸式状态栏过度不是太平滑,Demo的标题栏是蓝色，如果是白色就比较明显

**Comment by Hitomis** [comment]
你说的这两个问题应该是你改变状态栏导致的。和添加header应该没关系。你这种情况用1.5.0版本的就没问题。
之后的版本会强制改成兼容4.4以后状态栏可变的特性了。
感谢反馈。

**Comment by Vonnie0709** [comment]
沉浸式状态栏过度我还没验证，但是header的问题我验证了的，我把设置header注释了之后，该问题就不存在了，你可以试试的

**Comment by Hitomis** [comment]
你有试过不要改状态栏吗？

**Comment by Vonnie0709** [comment]
我刚刚刻意试了试
1.不修改状态栏并且添加header，动画错位 
2.不修改状态栏并且不添加header，动画正常

早上试过了修改状态栏后，结论一致，所以应该是header的问题，由于我项目代码量比较大，可能有纰漏，还请博主辛苦验证一下

**Comment by Hitomis** [comment]
没有视频。文字传递信息还是引起理解错误啊。
你的错位应该是整个动画播放的初始位置都不是你点击的那个item吧？
我理解的错位是之前那些 issues 所说的由于状态的问题。而导致上下有错位。没想到是整体错位。

**Comment by Hitomis** [comment]
> 我刚刚刻意试了试
> 1.不修改状态栏并且添加header，动画错位
> 2.不修改状态栏并且不添加header，动画正常
> 
> 早上试过了修改状态栏后，结论一致，所以应该是header的问题，由于我项目代码量比较大，可能有纰漏，还请博主辛苦验证一下

还有不懂请看项目中demo代码 RecyclerViewActivity 所示。

**Comment by Vonnie0709** [comment]
视频已经发送到邮箱

**Comment by Vonnie0709** [comment]
我测试使用代码和demo一致，唯一区别在于RecyclerView添加了header，其他没差，博主大可试试

**Comment by Hitomis** [comment]
> 我测试使用代码和demo一致，唯一区别在于RecyclerView添加了header，其他没差，博主大可试试

修改方式上面已经说了哈。你的position传错了。。。

**Comment by Vonnie0709** [comment]
好的

**Comment by Hitomis** [comment]
> 好的

1.5.2版本已经发布了。
现在已经支持 ListView 或者 RecyclerView 添加 header 或者 footer

**Comment by Vonnie0709** [comment]
感谢博主，稍后我再尝试尝试
