### ISSUE TITLE
一个列表里边的item包含1-9个动态生成的ImgView

### ISSUE THREAD

**Issue by LittlePenguinZ** [Hitomis/transferee#115]
一个RecyclerView列表里边的item包含1-9个动态生成的ImgView,是不是就不能用这个框架了，

**Comment by Hitomis** [comment]
描述的比较像微信朋友圈列表,每条朋友圈里面可能包含1-9张图片。
这种情形是可以用的。transferee 从第一个版本就可以这样用。

**Comment by LittlePenguinZ** [comment]
对，就是和朋友圈一样，是用bindRecyclerView这方式吗？，我试了bindImageView(imageView, listPath) 和bindRecyclerView 我弄了两次，总报错，求指点 谢谢

**Comment by Hitomis** [comment]
我想你是绑定错了RecyclerView。
是每个 item 里面的图片组被transferee绑定，而不是朋友圈这个 RecyclerView 被绑定。
如果猜想有误。请上代码。和报错日志

**Comment by LittlePenguinZ** [comment]
![image](https://user-images.githubusercontent.com/15098180/81643547-6160fb00-9458-11ea-875e-74eb6d0e9364.png)  这是我的代码

**Comment by LittlePenguinZ** [comment]
![image](https://user-images.githubusercontent.com/15098180/81643904-3d51e980-9459-11ea-8493-8a699ed768eb.png)
![image](https://user-images.githubusercontent.com/15098180/81643946-4f338c80-9459-11ea-9e2c-d618ee6e77b0.png)
这是动态生成的ImageView的代码

**Comment by LittlePenguinZ** [comment]
![image](https://user-images.githubusercontent.com/15098180/81644323-15af5100-945a-11ea-9033-5617f616da1a.png) 错误

**Comment by Hitomis** [comment]
错误是数组下标越界。还是你的传参有问题，readme 中我对每个参数有非常详细的解释。
你要保证你的 position 不能超过 SourceImageLIst 的范围。

鉴于文字交流效率太低，我刚添加了朋友圈样式的使用demo。你可以查看下代码
![image](https://user-images.githubusercontent.com/7991983/81648573-7ee69280-9461-11ea-8534-cf7f230e2144.png)

**Comment by LittlePenguinZ** [comment]
好的感谢

**Comment by LittlePenguinZ** [comment]
刚看了不太一样，你的图片是用RecyclerView 加载的，我的是在item里边自定义一个framelayout,然后再framelayout里边根据图片数量, 动态生成了1-9 的imgview

**Comment by Hitomis** [comment]
> 刚看了不太一样，你的图片是用RecyclerView 加载的，我的是在item里边自定义一个framelayout,然后再framelayout里边根据图片数量, 动态生成了1-9 的imgview

这不一样的道理吗？我的天。。不管你把你的容器换成 RecyclerView 还是你把api换成绑定ImageView。都一样的道理啊。
你仔细看看代码吧。
