### ISSUE TITLE
索引指示器位置问题

### ISSUE THREAD

**Issue by yueye410** [Hitomis/transferee#116]
默认索引指示器在上边，请问怎么调整到下边呢？
谢谢。

**Comment by Hitomis** [comment]
如果你使用 NumberIndexIndicator的话，实现方式默认位置就在上面。
如果你使用CircleIndexIndicator的话，实现方式默认位置在下面。
如果上面两种都不是你要的。你可以自己实现 IndexIndicator接口，去写你自己的索引指示器

**Comment by Hitomis** [comment]
如果你使用 NumberIndexIndicator的话，实现方式默认位置就在上面。
如果你使用CircleIndexIndicator的话，实现方式默认位置在下面。
如果上面两种都不是你要的。你可以自己实现 IndexIndicator接口，去写你自己的索引指示器
