### ISSUE TITLE
聊天界面,多张图片预览怎么做?

### ISSUE THREAD

**Issue by guozhicheng1987** [Hitomis/transferee#117]
我测试绑定ImageView,展示多个图片集,报数组越界.

**Comment by Hitomis** [comment]
报数组越界一般都是你的 position 传递有问题。position  和你传递的 sourceImageList 或者 sourceUriList 是对应的

**Comment by Hitomis** [comment]
谢谢你的反馈，应该是最近几版改出问题来了，没发现。最近几天马上会上一个大版本。这个问题会一并修复

**Comment by guozhicheng1987** [comment]
好的，谢谢您的回复。还有一个就是图片展开后状态栏样式是否可以设置。



---原始邮件---
发件人: "Vans Z"<notifications@github.com&gt;
发送时间: 2020年5月25日(周一) 晚上10:03
收件人: "Hitomis/transferee"<transferee@noreply.github.com&gt;;
抄送: "Author"<author@noreply.github.com&gt;;"moshengsheng"<25080501@qq.com&gt;;
主题: Re: [Hitomis/transferee] 聊天界面,多张图片预览怎么做? (#117)




 
谢谢你的反馈，应该是最近几版改出问题来了，没发现。最近几天马上会上一个大版本。这个问题会一并修复

**Comment by Hitomis** [comment]
transferee 内部没有改状态栏和导航栏，就是怕耦合问题，所以这个还是用户自己控制比较好。demo 里面是用的ImmersionBar 管理的状态栏。你可以 check 下

**Comment by guozhicheng1987** [comment]
好的，谢谢。



---原始邮件---
发件人: "Vans Z"<notifications@github.com&gt;
发送时间: 2020年5月25日(周一) 晚上10:23
收件人: "Hitomis/transferee"<transferee@noreply.github.com&gt;;
抄送: "Author"<author@noreply.github.com&gt;;"moshengsheng"<25080501@qq.com&gt;;
主题: Re: [Hitomis/transferee] 聊天界面,多张图片预览怎么做? (#117)




 
transferee 内部没有改状态栏和导航栏，就是怕耦合问题，所以这个还是用户自己控制比较好。demo 里面是用的ImmersionBar 管理的状态栏。你可以 check 下

**Comment by Hitomis** [comment]
你提的状态栏样式是否可以设置这个问题，我发现应该是屏幕适配的问题。这个问题，下个版本也会一起修复

**Comment by guozhicheng1987** [comment]
好的。谢谢。



---原始邮件---
发件人: "Vans Z"<notifications@github.com&gt;
发送时间: 2020年5月27日(周三) 中午11:48
收件人: "Hitomis/transferee"<transferee@noreply.github.com&gt;;
抄送: "Author"<author@noreply.github.com&gt;;"moshengsheng"<25080501@qq.com&gt;;
主题: Re: [Hitomis/transferee] 聊天界面,多张图片预览怎么做? (#117)




 
你提的状态栏样式是否可以设置这个问题，我发现应该是屏幕适配的问题。这个问题，下个版本也会一起修复

**Comment by Hitomis** [comment]
> 好的。谢谢。
> […](#)
> ---原始邮件--- 发件人: "Vans Z"<notifications@github.com&gt; 发送时间: 2020年5月27日(周三) 中午11:48 收件人: "Hitomis/transferee"<transferee@noreply.github.com&gt;; 抄送: "Author"<author@noreply.github.com&gt;;"moshengsheng"<25080501@qq.com&gt;; 主题: Re: [Hitomis/transferee] 聊天界面,多张图片预览怎么做? (#117) 你提的状态栏样式是否可以设置这个问题，我发现应该是屏幕适配的问题。这个问题，下个版本也会一起修复 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

v 1.6 已发布 上述问题已经修复。文档和demo，以及 demo.apk 全部更新

**Comment by guozhicheng1987** [comment]
好的，谢谢！



---原始邮件---
发件人: "Vans Z"<notifications@github.com&gt;
发送时间: 2020年5月28日(周四) 下午2:12
收件人: "Hitomis/transferee"<transferee@noreply.github.com&gt;;
抄送: "Author"<author@noreply.github.com&gt;;"moshengsheng"<25080501@qq.com&gt;;
主题: Re: [Hitomis/transferee] 聊天界面,多张图片预览怎么做? (#117)




  
好的。谢谢。
 …
 ---原始邮件--- 发件人: "Vans Z"<notifications@github.com&gt; 发送时间: 2020年5月27日(周三) 中午11:48 收件人: "Hitomis/transferee"<transferee@noreply.github.com&gt;; 抄送: "Author"<author@noreply.github.com&gt;;"moshengsheng"<25080501@qq.com&gt;; 主题: Re: [Hitomis/transferee] 聊天界面,多张图片预览怎么做? (#117) 你提的状态栏样式是否可以设置这个问题，我发现应该是屏幕适配的问题。这个问题，下个版本也会一起修复 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.
  
v 1.6 已发布 上述问题已经修复。文档和demo，以及 demo.apk 全部更新
