### ISSUE TITLE
#适配问题

### ISSUE THREAD

**Issue by zhangdehui** [Hitomis/transferee#118]
①华为手机PAR-TL00，EMUI版本9.1.0，Android版本9，这个库在这个手型号手机上运行时，关闭查看大图后，状态栏的黑色没法消失。
②如果在recyclerview查看大图，配置.enableDragHide(true)
                        .setCustomView(View.inflate(getBaseContext(), R.layout.layout_custom, null))
这两个属性下去，那个自定义view的文字有时有显示有时不显示

**Comment by Hitomis** [comment]
感谢反馈，最近正准备发布下个版本，这些问题会一起修复提交上去------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;zhangdehui&quot;<notifications@github.com&gt;
发送时间:&nbsp;2020年5月26日(星期二) 晚上7:36
收件人:&nbsp;&quot;Hitomis/transferee&quot;<transferee@noreply.github.com&gt;;
抄送:&nbsp;&quot;Subscribed&quot;<subscribed@noreply.github.com&gt;;
主题:&nbsp;[Hitomis/transferee] #适配问题 (#118)

**Comment by Hitomis** [comment]
v 1.6 已发布 上述问题已经修复。文档和demo，以及 demo.apk 全部更新
