### ISSUE TITLE
绑定单个imageView 问题

### ISSUE THREAD

**Issue by Ye83** [Hitomis/transferee#119]
![image](https://user-images.githubusercontent.com/17722346/83099594-61136180-a0e0-11ea-8c84-54a78ce4a725.png)
用以上代码显示图片，过渡过程总是先显示PlaceHolder  的图片，然后再显示想要显示的网络图片。如果方便，可以加下您的微信，给您展示下吗

**Comment by Ye83** [comment]
测试了一下，用demo 中的
![image](https://user-images.githubusercontent.com/17722346/83099837-f9114b00-a0e0-11ea-93de-bb5039e950f8.png)这zhang 这张图不会有这样的情况，但是用自己的图片就会。图片大小分别是42k  和  
676kb

**Comment by Hitomis** [comment]
正在发布1.6.0版本。你等下用新版本试一试

**Comment by Hitomis** [comment]
兄弟。1.6最新大版本已经发布了，demo 和文档也更加详细了，demo apk 也更新了，你可以看看
