### ISSUE TITLE
一点小小的优化

### ISSUE THREAD

**Issue by lydlovezjr** [Hitomis/transferee#120]
<img width="337" alt="1591687771(1)" src="https://user-images.githubusercontent.com/19246347/84118841-20afce00-aa66-11ea-8663-df7e567ce070.png">
刘海屏,指示器被挡住.

**Comment by Hitomis** [comment]
上个版本还是存在一些ui兼容问题。目前已经在最新的版本中修复了。等测试完成后就会发新版本

**Comment by Hitomis** [comment]
1.6.1版本已发布，可下载试用
