### ISSUE TITLE
> https://img.ibaodashi.com/hermes/56f5c408ab03e7c3f14532050cf11254.jpg 图片放这张就崩了。GlideImageLoader加载，需要优化图片加载。

### ISSUE THREAD

**Issue by mahao521** [Hitomis/transferee#121]
> https://img.ibaodashi.com/hermes/56f5c408ab03e7c3f14532050cf11254.jpg 图片放这张就崩了。GlideImageLoader加载，需要优化图片加载。
> 设置customView作用是干嘛，和数据源以及viewpager没有绑定嘛，除非就是单张显示。
> 自定义indictor的作用就是显示自定的view。customView 就感觉没啥用了吧。
> 还需要从下向上拖拽消失的功能哦。

1.图片加载优化已经在进行中了，不过最近太忙，可能要等一段时间才能上线了
2.customeView 是为了自定义 transferee 主界面用的，很多用户都有这个需求，比如微博的图片查看，右下角有点赞，评论等按钮，右上角有关注，更多等菜单。
3.从下向上拖拽消失的功能不考虑做了，因为和拖拽关闭功能重复，或者你可以自己做，推上来

_Originally posted by @Hitomis in https://github.com/Hitomis/transferee/issues/107#issuecomment-638741313_

**Comment by Hitomis** [comment]
请问这个 issues 是什么意思？这个问题1.6.1版本已经解决了

**Comment by mahao521** [comment]
代码没完全看懂，改了几行代码就实现了，感谢大佬。然后图片showImage使用asBitmap，into(imageview) 然后用glide那一套，就没bug了。位置换成了getLocationOnScreen()；接下来准备把glide的缓存拿过来，自己就不缓存了，就不需要progressbar了，点击就是缩放动画。嘿嘿嘿。
