### ISSUE TITLE
拖动关闭的时候会先闪一下

### ISSUE THREAD

**Issue by 643063150** [Hitomis/transferee#122]
拖动关闭时，渐变的颜色没有保持，会先闪一下，再关闭  https://github.com/stfalcon-studio/FrescoImageViewer 目前用的库时基于这个库的修改，不会闪动，但是没有加动画

**Comment by Hitomis** [comment]
请说明
1.当前使用库版本
2.运行的手机
3.使用代码
4.最终的是，demo.apk 在你手机上是不是也有这个问题？

**Comment by 643063150** [comment]
用的就是demo的apk  ，第一次用还崩溃了一次，没用真机用的模拟器，不过闪动问题我发的库在模拟器上也是没问题的 我安装到真机看一下
![caogou](https://user-images.githubusercontent.com/11732536/84356154-60a5bb00-abf6-11ea-9ac0-fd4b715bf758.gif)

**Comment by Hitomis** [comment]
- 

> 用的就是demo的apk ，第一次用还崩溃了一次，没用真机用的模拟器，不过闪动问题我发的库在模拟器上也是没问题的 我安装到真机看一下
> ![caogou](https://user-images.githubusercontent.com/11732536/84356154-60a5bb00-abf6-11ea-9ac0-fd4b715bf758.gif)

一切请以真机为准，感谢

**Comment by 643063150** [comment]
试了下 真机 型号是华为的华为畅享9 Plus,也会闪，不过感知没有模拟器这么强烈，可以接收的范围

**Comment by Hitomis** [comment]
> 试了下 真机 型号是华为的华为畅享9 Plus,也会闪，不过感知没有模拟器这么强烈，可以接收的范围

能上个视频吗？

**Comment by 643063150** [comment]
![SmartSelect_20200611-153227_Video Player](https://user-images.githubusercontent.com/11732536/84357862-e32f7a00-abf8-11ea-987c-10df3f5bdb6a.gif)
这华为没有录屏功能，我用自己的s20试了下也是轻微的闪动 ，不仔细看看不出，模拟器那么严重估计是模拟器的渲染有问题吧

**Comment by 643063150** [comment]
![SmartSelect_20200611-153227_Video Player](https://user-images.githubusercontent.com/11732536/84358088-33a6d780-abf9-11ea-89f3-aa09f2ca7944.gif)

**Comment by 643063150** [comment]
心态崩了，传的图一直裂，不过没关系 真机应该是没有问题的

**Comment by Hitomis** [comment]
> 心态崩了，传的图一直裂，不过没关系 真机应该是没有问题的

没事，兄弟，我看到了你传的两幅图，这个上面的动画是正常的。。而且你可以在用的时候，setDuration(10000) 放慢速度来看。。。因为这个背景渐变是由手指移动来控制的额，你手指动的只要足够快。这个渐变就可以快到让你觉得颜色是闪屏，特别是手指要抬起的一瞬间，会甩一下手指。那一下就更明显了。

**Comment by 643063150** [comment]
嗯，感谢解答
