### ISSUE TITLE
安卓x冲突有的解决吗，我把代码弄到项目里了，但现在弹出的不是全屏

### ISSUE THREAD

**Issue by rookieYJ** [Hitomis/transferee#124]

**Comment by rookieYJ** [comment]
![微信图片_20200611171525](https://user-images.githubusercontent.com/34829467/84368166-cfd7db00-ac07-11ea-9859-c9d0d64c0c2f.jpg)

**Comment by Hitomis** [comment]
代码？你不是用的jitpack 依赖？

**Comment by rookieYJ** [comment]
依赖进去报错啊，一直有冲突，androidx的

**Comment by rookieYJ** [comment]
点击进入查看的时候状态栏不见了，退出后我的布局也上去了，没有恢复

**Comment by Hitomis** [comment]
这个应该是dialog style 和状态栏以及导航栏修改的问题。因为你是拿的代码用，我这边也不知道你做了什么修改，所以本质上我是没法帮助你的。你只能多看看demo了
或者你把你的项目升级为 androidx 项目，as自带一键升级。就是换一些官方的包为androidx的。建议你试一试。

**Comment by rookieYJ** [comment]
as得升级到3.2吧

**Comment by Hitomis** [comment]
> as得升级到3.2吧

as 最新版4.0了。。。
ide能用尽量用最新的好。。。
