### ISSUE TITLE
如何使图片预览的时候全屏

### ISSUE THREAD

**Issue by Yuphee** [Hitomis/transferee#14]

**Comment by Hitomis** [comment]
本项目因为有一个严重问题无法解决，现在正在重构中···

**Comment by Yuphee** [comment]
我发现在原先activity上添加view的形式很难使状态栏能达到很好的隐藏效果，我看过其他一些实现方式比如再起一个activity或者是一个dialog

**Comment by Hitomis** [comment]
额，也许你对 WMS 不熟悉，你应该是在Android 4.4 以上系统（即状态栏可自定义的新版本特性）上出现的这个问题，这个问题即使是用 Activity 和 Dialog 也会出现的（当然有解决方案）

**Comment by Hitomis** [comment]
目前重构版本已经初步完成。您可以 pull 下来进行使用，如有问题请提 Issues
