### ISSUE TITLE
这个如何删除某一item呢、看代码感觉好难改的动啊、不知道你后续会不会增加这个功能

### ISSUE THREAD

**Issue by hebrew** [Hitomis/transferee#15]

**Comment by Hitomis** [comment]
谢谢您的意见，不知道是不是你没有明白我这个库的主要职责（主要职责：从缩略图大原图的无缝切换，提升用户体验，以及图片浏览功能，并没有你说的为了删除 什么item 而设计的），还是你的问题让我不大明白？
