### ISSUE TITLE
关于 adjustTopAndBottom 的问题

### ISSUE THREAD

**Issue by hhaappy163** [Hitomis/transferee#155]
show();方法里直接调用了
adjustTopAndBottom();
然后调用了
            ImmersionBar.with(activity, transDialog)
                    .transparentNavigationBar()
                    .init();
这直接改变了activity里状态栏的设置 ， toolbar直接跑到状态栏去了。
退出后也不给复原，也太不友好了。强制干扰父级界面了。

**Comment by aaronzzx** [comment]
复议

**Comment by hhaappy163** [comment]
> 复议

这个老哥好像没有维护了  

推荐使用这个https://github.com/iielse/imageviewer

**Comment by Hitomis** [comment]
在使用 transferee的页面调用下面代码可以解决
ImmersionBar.with(this).titleBar(R.id.tool_bar).init();
