### ISSUE TITLE
GridViewActivity只有一张图片的时候黑屏

### ISSUE THREAD

**Issue by lynleyy** [Hitomis/transferee#16]

**Comment by Hitomis** [comment]
不好意思，目前正在重构，所有代码都是有问题的，发正式版的时候，我会发公告的，还请多关注

**Comment by xiaosuda88** [comment]
这个问题好像是那个transferLayout中的viewpager默认加载三张图片，左中右各一张，如果gridview中只有一张图片这样的话就会出问题，建议在transferLayout中作一个判断

**Comment by Hitomis** [comment]
目前重构版本已经初步完成。您可以 pull 下来进行使用，如有问题请提 Issues
