### ISSUE TITLE
类似微博长图浏览的功能实现了吗？

### ISSUE THREAD

**Issue by jayleco** [Hitomis/transferee#18]
大图浏览长图浏览这种需求实现了吗？
subsampling-scale-image-view我看好多大图浏览用的这个

**Comment by Hitomis** [comment]
谢谢你提的意见，这一功能已提到计划安排当中，在下一次版本中应该就能实现了，请耐心等候！
thx

**Comment by Hitomis** [comment]
目前已经对长图浏览的功能简单的进行了支持，subsampling-scale-image-view 设计是继承 View 实现。无法使用
