### ISSUE TITLE
不错，，但有个小八哥

### ISSUE THREAD

**Issue by yezihengok** [Hitomis/transferee#20]
首先感谢分享 效果很好 类似5.0的转场动画，，不过发现了个小bug ,多加入几张图片让GridView 可以滑动的时候 `点击会包空指针

`05-12 11:26:22.761 19532-19532/com.hitomi.transferimage E/AndroidRuntime: FATAL EXCEPTION: main java.lang.NullPointerException at com.hitomi.transferimage.activity.BaseActivity.wrapOriginImageViewList(BaseActivity.java:45)``

**Comment by Hitomis** [comment]
我在 Demo 里面把 GridView  高度固定了，GridView 在获取有多少 Item 的时候，获取的时候可见 Item 的数目，如果图片多了必定有几个不可见，需要滑上去才能看的见，这时候使用 wrapOriginImageViewList 肯定会出问题，这个方法只是 Demo 代码，如果你要修改，你在 xml 文件中把 GridView的高度改成 wrap_content 就行了，或者你自己亲自修改 wrapOriginImageViewList  方法

**Comment by Hitomis** [comment]
想了想，我自己把 GridView  的高度改成 wrap_content 吧，免得产生不必要的误解

**Comment by yezihengok** [comment]
腻害了，这回复速度..
