### ISSUE TITLE
全屏大图页面布局能否自定义？

### ISSUE THREAD

**Issue by fuguiniao** [Hitomis/transferee#21]
全屏大图页面布局能否自定义？比如要显示图片的描述文字

**Comment by Hitomis** [comment]
我们应该遵循对修改关闭，对扩展开放的原则。
所以全屏大图页面布局无法做到自定义，这样会破坏一些既有的规则，从而让 transferee 无法正常工作。
如果后期实在是有这个需求，我可以提供一个扩展接口。工作模式就像 indexIndicator 接口这样。
谢谢您的提议~

**Comment by JadonPsycho** [comment]
我也想这么说 例如微信长按可以扫描识别二维码，保存图片等功能 需要有这些接口
