### ISSUE TITLE
图片超过一屏报错

### ISSUE THREAD

**Issue by Silnt** [Hitomis/transferee#23]
GridView 中的图片超过一屏 后点击图片报错
java.lang.NullPointerException: Attempt to invoke virtual method 'android.view.View android.widget.LinearLayout.getChildAt(int)' on a null object reference at com.hitomi.transferimage.activity.BaseActivity.wrapOriginImageViewList(BaseActivity.java:50)

**Comment by Hitomis** [comment]
详见 .wrapOriginImageViewList  注释
或者
[#20](https://github.com/Hitomis/transferee/issues/20)
