### ISSUE TITLE
查看图片返回的时候dialog消失后屏幕闪一下

### ISSUE THREAD

**Issue by zguangjing** [Hitomis/transferee#25]
建议在调用Activity的oncreate中加入或者BaseActivity
        /**
         * 全屏不重绘
         */
        getWindow().addFlags(WindowManager.LayoutParams.FLAG_LAYOUT_IN_SCREEN);
        getWindow().addFlags(WindowManager.LayoutParams.FLAG_LAYOUT_NO_LIMITS);

**Comment by Hitomis** [comment]
谢谢你的建议·

**Comment by lfei1789** [comment]
如果在页面中添加全屏，那状态栏就需要特别处理了
