### ISSUE TITLE
webview上查看图片没有arraylist<imageview>

### ISSUE THREAD

**Issue by terryyhl** [Hitomis/transferee#27]
如果没有arraylist<imaegview>如何使用这个控件，改掉这个ill异常么？

**Comment by Hitomis** [comment]
编写 transferee 组件就是为了更好的交互从而解决从缩略图到详情图过渡的问题。
originImageList 是 transferee 的核心属性，有了 originImage 才能有小图到大图的转变。
如果你没有 originImage 。那为什么还要使用 transferee 呢？
仅仅使用普通的 dialog 来显示你 WebView 上的图片就可以了。

**Comment by terryyhl** [comment]
glide不支持4.0

**Comment by Hitomis** [comment]
你可以仅仅使用 transferee 组件，实现 imageLoader 接口，去实现自己的图片加载器。
glide 4 在版本稳定后，我会考虑去扩展一个 glide4 图片加载器。

**Comment by flztsj** [comment]
glide 4 已经稳定了

**Comment by flztsj** [comment]
个人觉得库能兼容下这个case也挺好，这样也就不用再重写相关逻辑了
