### ISSUE TITLE
Glide浏览很卡，Imageloader加载长图很模糊

### ISSUE THREAD

**Issue by d19890415** [Hitomis/transferee#29]
1. Glide测试（无缩略图） 使用时候明显感觉比较卡，掉帧验证，不知道你有没有发现

2. Imageloader加载长图很模糊，但是用Glide加载同样的长图没问题。
长图链接：http://ww1.sinaimg.cn/large/9be2329dgw1etlyb1yu49j20c82p6qc1.jpg

**Comment by Hitomis** [comment]
1.请问你使用的是什么手机？需要提供型号，系统版本，厂家等信息。
2.目前transferee不支持长图浏览。

**Comment by d19890415** [comment]
问题1，我是红米note3，5.0安卓系统，miui，比较低配的手机。在 “Glide测试（无缩略图）” 任何手势带来的动画都比较卡，帧率明显低于通过Imageloader加载的

问题2，经过我个人的修改，在初始化的时候，加上 .imageScaleType(ImageScaleType.NONE)。加载长图就不会模糊了

**Comment by Hitomis** [comment]
目前我使用的是3年前小米公司出的红米1。目前市值150rmb不到。测试 transferee 依然比较流畅
你提供的长图url，我在红米1手机上打开感觉很清晰。

最好能提供截图等直观表现的文件来说明你的问题。
thx.

**Comment by Hitomis** [comment]
长度模糊的问题，是因为 略图的 ScaleType 需要设置为 centerCrop

**Comment by d19890415** [comment]
关于适配长图的问题，我发现现在的问题就是，打开长图，显示的是长图中心部位。理想化的应该是自动滚动到长图的顶部。

我的修改方案是：在photoview类里的initBase方法的结尾处（即 第336行代码 mFromInfo = null; 的下面）加上：

        if (imgh > imgw *3) { //图片高度>宽度*3 判定为长图
            mAnimaMatrix.postTranslate(0, -mImgRect.top);
            mTranslateY -= mImgRect.top;
            executeTranslate();
        }

就可实现打开长图自动显示顶部
目前短暂测试 没发现问题。不知道是否有隐患或者不合适之处

**Comment by Hitomis** [comment]
谢谢你的方案。目前是可以的。
