### ISSUE TITLE
不能定制吗？

### ISSUE THREAD

**Issue by JakeWoki** [Hitomis/transferee#30]
有可能不需要引指器，增加显示标题、保存图片到本地、识别二维码等功能。TransferLayout最好公开。
用转场动画可能更好，虽然在5.0以下没兼容。
只看了一点代码，可能说的有错

**Comment by Hitomis** [comment]
好的，对你这个需求，可以考虑在下个版本中开放出来

**Comment by Hitomis** [comment]
transferee 主界面的 UI 自定义，可以考虑设计这个功能。
不过索引指示器，大多数还是需要的。transferee提供了接口，
可以自定义你的索引指示器，如果你不需要显示索引指示器，
那么你可以给transferee 一个空的 IIndexIndicator 的实现类就好了。

**Comment by JakeWoki** [comment]
有没有试过元素共享？元素共享也可以实现这个效果
[SharedElementDemo](https://github.com/lin18/SharedElementDemo)

**Comment by Hitomis** [comment]
这是5.0以上的特性。transferee就是为了兼容5.0以下
