### ISSUE TITLE
用recycleview复用的时候,里面的imgaview集合加的是上一个imagview

### ISSUE THREAD

**Issue by lodgkk** [Hitomis/transferee#35]
复用的时候,会把上一个imageview加进去,然后点击会再上一个imageview的地方放到到全屏,目前解决方法是:
private SparseArray<List<ImageView>> imgs = new SparseArray<>();

public List<ImageView> getOriginImgList(int position) {
        return imgs.get(position);
}
在onBindViewHolder的时候每个position都加一个imageview的集合,把你需要显示的imageview都加进去

**Comment by Hitomis** [comment]
个人建议你调试下自己的代码，其他用户使用recycleview没有问题；
谢谢你的建议
