### ISSUE TITLE
现在Glide已经到4.0了,能支持到4.0吗,因为里面的方法都变了,所以GlideLoader不能用了

### ISSUE THREAD

**Issue by lodgkk** [Hitomis/transferee#36]
现在Glide已经到4.0了,能支持到4.0吗,因为里面的方法都变了,所以GlideLoader不能用了

**Comment by Hitomis** [comment]
提供 imageLoader 就是为了解决这样的问题。
市面上图片加载器如此多，请谅解作者没有精力去为每个加载器，每一个版本提供一个实现。
你可以自己显示 imageloader 自己去实现自己想要的加载器。
t h x
