### ISSUE TITLE
关于在“Glide测试(无缩略图)”页面中从viewpager退出来以后列表图片仍然显示占位图的BUG

### ISSUE THREAD

**Issue by yaochangliang159** [Hitomis/transferee#40]
操作步骤如下:
1，打开 Glide测试(无缩略图) 界面
2，9张图片全部显示占位图，表示正在加载状态，这时候直接点击其中的某一张图片，跳转到viewpager界面，progreesspie也显示出来，表示正在加载图片，等到加载完图片，图片在viewpager中完全显示，这时候立马摁返回键，回到列表界面，发现列表中刚刚点击的那张图片还是处于占位图的状态。
我期望出现的现象：
在dialog中已经加载图片完毕了，摁返回键退出viewpager界面，这时候列表中刚刚点击的那张图片应该显示图片，因为我刚才在viewpager里面加载完了。

另外，你这个库真的很棒！！！！支持作者！！！！

**Comment by Hitomis** [comment]
这个是 Glide 的特性和 Glide 的缓存bug所导致的，建议你可以细细研究下 Glide 的缓存机制，如果你用GlideImageLoader 这个问题是无法解决的，只能规避。
规避方案请详见[GlideNoThumActivity](https://github.com/Hitomis/transferee/blob/master/app/src/main/java/com/hitomi/transferimage/activity/glide/GlideNoThumActivity.java) 93 - 103 code。
谢谢支持
