### ISSUE TITLE
在Fragment和Activity中一起使用会报错

### ISSUE THREAD

**Issue by Luopan1** [Hitomis/transferee#41]
我在Fragment中onCreat()中初始化，单独使用没问题，然后在BaseActivity中初始化，然后在别的Activity中使用时，第一次正常显示，然后在去Fragment中点击图片，没什么问题，然后在回到这个Activity中点击图片 ，点击图片不显示大图，按下返回键就显示大图。但是Activity已经onDestory了，大图仍然显示，在按下返回键程序就崩了。

**Comment by Hitomis** [comment]
用最新的代码。别用gradle导入的老版本
