### ISSUE TITLE
查看大图返回,状态栏会闪一下

### ISSUE THREAD

**Issue by umeitime** [Hitomis/transferee#42]
查看大图返回,状态栏会闪一下

**Comment by umeitime** [comment]
`private void createDialog() {
        transDialog = new AlertDialog.Builder(context, getDialogStyle())
                .setView(transLayout)
                .create();
        //解决状态栏闪动
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.LOLLIPOP) {
            transDialog.getWindow().addFlags(WindowManager.LayoutParams.FLAG_DRAWS_SYSTEM_BAR_BACKGROUNDS);
        }

        transDialog.setOnShowListener(this);
        transDialog.setOnKeyListener(this);
    }`

**Comment by mickyliu945** [comment]
我使用：transDialog.getWindow().addFlags(WindowManager.LayoutParams.FLAG_DRAWS_SYSTEM_BAR_BACKGROUNDS); }
还是一样显示大图状态栏消失返回状态栏又显示。
使用如下代码解决了状态栏消失的问题，只是显示大图的时候会出现状态栏。
transDialog.getWindow().addFlags(WindowManager.LayoutParams.FLAG_FORCE_NOT_FULLSCREEN);
