### ISSUE TITLE
可以在点击放大时候，右下角增加个下载按钮，可以下载保存到本地吗

### ISSUE THREAD

**Issue by iamzj** [Hitomis/transferee#46]
目前只有长按保存，可否自定义查看大图时下载

**Comment by zwwxj** [comment]
我也有这个需求，可以在底部就一个保存按钮吗？保存到本地相册

**Comment by Hitomis** [comment]
目前最新版本已经提供了api(具体查看demo代码和ReadMe)，可以直接获取到图片文件，然后可以通过长按事件弹起一个弹窗。如果非要修改预览大图的界面在里面加一些按钮，目前暂时没有提供。不过可以自己修改源码，比较简单。后期如果有许多人有这个需求，我会考虑抽一个接口
@ @iamzj @zwwxj
