### ISSUE TITLE
使用Glide 不能使用缩略图么？

### ISSUE THREAD

**Issue by hyr0318** [Hitomis/transferee#48]

**Comment by Hitomis** [comment]
使用 Glide4Imageloader 是可以的。glide4 修复了 glide3 的一个bug,所以 glide4 作为图片加载器是可以使用缩略图的。具体可以参考 (GlideNormalActivity)[https://github.com/Hitomis/transferee/blob/master/app/src/main/java/com/hitomi/transferimage/activity/glide/GlideNormalActivity.java]
