### ISSUE TITLE
与Fresco搭配使用的问题

### ISSUE THREAD

**Issue by BeetleSxy** [Hitomis/transferee#54]
因为Fresco的问题无法使用共享动画，如果与Fresco搭配使用会有退出大图后图片不显示问题，可以增加方式来决定是否使用共享动画吗？

**Comment by Hitomis** [comment]
考虑到transferee的一些特性，目前准备去除图片加载器的接口，内置一个默认的图片加载器，所以目前不会考虑使用fresco
