### ISSUE TITLE
返回时 Toolbar 会闪动

### ISSUE THREAD

**Issue by umeitime** [Hitomis/transferee#58]
返回时 Toolbar 会界面顶部往下移动。

**Comment by nathanzhang666** [comment]
老铁，这个问题你是怎么解决的

**Comment by Wesley254619** [comment]
往下移的原因是因为 Transferee 里 getDialogStyle 设置的 Theme 为 Fullscreen，把它去掉，换成 android.R.style.Theme_Translucent_NoTitleBar 就好了
