### ISSUE TITLE
感谢作者开源这个库，想请教几个问题

### ISSUE THREAD

**Issue by nginnx** [Hitomis/transferee#64]
- 首先对作者表示感谢，这个库很好，实现的代码也非常棒
阅读源码的过程中，学习到了很多知识，也有一些疑惑
- 在读TransferImageView的onDraw方法时,对onDraw中的这段代码一直不太懂，方便的话，可否讲解一下这段代码的用处，如果可以简单讲解一下onDraw，或者补充一些注释的话，就再好不过了
```
int saveCount = canvas.getSaveCount();
            canvas.save();
            calcBmpMatrix();
            canvas.translate(transform.rect.left, transform.rect.top);
            canvas.clipRect(0, 0, transform.rect.width, transform.rect.height);
            canvas.concat(transMatrix);
            getDrawable().draw(canvas);
            canvas.restoreToCount(saveCount);
```
- 对transform.clip()有一些疑问，能否讲解一下，oriImage是center crop时,是怎样通过clip过渡到大图的呢? 如果大图是一个长图的话，又是怎样一个逻辑呢?
- 用了几天的时间,尝试将项目修改为微信的图片预览那样,
从缩略图 ===> 过渡到填满屏幕的缩略图 ===> 加载网络原图 ===> 显示原图
改了transferImage非常多的代码才实现
如果靠 作者你 抽象出来的state，要怎样实现这样的效果呢?
- 希望作者大大能不吝赐教，再次表示对作者开源这个库的感谢 !

**Comment by Hitomis** [comment]
int saveCount = canvas.getSaveCount();
            canvas.save();  // 缓存一张画布
            calcBmpMatrix();  // 依据动画类型计算此刻图像的矩阵
            canvas.translate(transform.rect.left, transform.rect.top); // 画布位移
            canvas.clipRect(0, 0, transform.rect.width, transform.rect.height); // 画布裁剪
            canvas.concat(transMatrix); // 使用之前计算得出的图像矩阵信息处理画布，说白了就是让canvas依据矩阵信息进行变换
            getDrawable().draw(canvas);  // 将图像绘制到最后处理好了的画布中
            canvas.restoreToCount(saveCount); 还原缓存的中图像到画布当中，与canvas.save成对出现

如果还不懂，我说几个知识点你自己去网上查一下看看，就能明白
1.Android Matrix 矩阵变化
2.Android canvas 常规操作
3.Android 画布双缓存，分层绘图

**Comment by cmtiger2018** [comment]
@nginnx 大佬我也正好遇到这个问题了（原始图片是 center crop时，过渡到大图）， 请问下你是如何来搞的？
