### ISSUE TITLE
支持不传imageview或绑定listview吗

### ISSUE THREAD

**Issue by umeitime** [Hitomis/transferee#69]
我的是新闻阅读资讯页面，我想简单的直接打开图片浏览页，直接使用默认动画就可以了。

**Comment by umeitime** [comment]
`private void fillOriginImages() {
        List<ImageView> originImageList = new ArrayList<>();
        if (transConfig.getRecyclerView() != null) {
            fillByRecyclerView(originImageList);
            transConfig.setOriginImageList(originImageList);
        } else if (transConfig.getListView() != null) {
            fillByListView(originImageList);
            transConfig.setOriginImageList(originImageList);
        }
    }`
如果不绑定listView或者recyclerView这个里面代码需要修改，不然会报错。

**Comment by S-Co** [comment]
@umeitime 老铁你现在怎么处理的

**Comment by Hitomis** [comment]
transferee 是一个关注从小图到大图无缝切换效果的库，需要缩略图的基本支持，目前已经支持直接绑定 ImageView , RecyclerView, LIstView 使用
