### ISSUE TITLE
bugly 报错：java.lang.NullPointerException

### ISSUE THREAD

**Issue by Yogurtla** [Hitomis/transferee#74]
Attempt to invoke virtual method 'int android.graphics.drawable.Drawable.getIntrinsicWidth()' on a null object reference

com.hitomi.tilibrary.view.image.TransferImage.b(TransferImage.java:112)
--
2 com.hitomi.tilibrary.view.image.TransferImage.a(TransferImage.java:102)
3 com.hitomi.tilibrary.transfer.a.a(EmptyThumState.java:175)
4 com.hitomi.tilibrary.transfer.a.b(EmptyThumState.java:159)
5 com.hitomi.tilibrary.transfer.a.a(EmptyThumState.java:29)
6 com.hitomi.tilibrary.transfer.d.a(TransferAdapter.java:125)
7 com.hitomi.tilibrary.transfer.d.instantiateItem(TransferAdapter.java:96)
8 android.support.v4.view.ViewPager.addNewItem(ViewPager.java:1004)
9 android.support.v4.view.ViewPager.populate(ViewPager.java:1152)
10 android.support.v4.view.ViewPager.populate(ViewPager.java:1086)
11 android.support.v4.view.ViewPager.onMeasure(ViewPager.java:1616)
12 android.view.View.measure(View.java:22216)
13 android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6671)
14 android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
15 android.view.View.measure(View.java:22216)
16 android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6671)
17 android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
18 android.view.View.measure(View.java:22216)
19 android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6671)
20 android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
21 android.view.View.measure(View.java:22216)
22 android.support.v7.widget.AlertDialogLayout.tryOnMeasure(AlertDialogLayout.java:133)
23 android.support.v7.widget.AlertDialogLayout.onMeasure(AlertDialogLayout.java:63)
24 android.view.View.measure(View.java:22216)
25 android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6671)
26 android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
27 android.support.v7.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:141)
28 android.view.View.measure(View.java:22216)
29 android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6671)
30 android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1539)
31 android.widget.LinearLayout.measureVertical(LinearLayout.java:823)
32 android.widget.LinearLayout.onMeasure(LinearLayout.java:702)
33 android.view.View.measure(View.java:22216)
34 android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6671)
35 android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
36 android.view.View.measure(View.java:22216)
37 android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6671)
38 android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1539)
39 android.widget.LinearLayout.measureVertical(LinearLayout.java:823)
40 android.widget.LinearLayout.onMeasure(LinearLayout.java:702)
41 android.view.View.measure(View.java:22216)
42 android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6671)
43 android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
44 com.android.internal.policy.DecorView.onMeasure(DecorView.java:831)
45 android.view.View.measure(View.java:22216)
46 android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2589)
47 android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1631)
48 android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1885)

**Comment by Yogurtla** [comment]
Android 8.0.0,level 26

ROM

HuaWei/EMOTION

CPU架构

arm64-v8a
荣耀 BKL AL00

**Comment by Hitomis** [comment]
用的是当前最新版本么？

**Comment by Yogurtla** [comment]
> 用的是当前最新版本么？

是的，最新版本，com.github.Hitomis.transferee:Transferee:v1.1.0

**Comment by DRAWCORE** [comment]
> > 用的是当前最新版本么？
> 
> 是的，最新版本，com.github.Hitomis.transferee:Transferee:v1.1.0

直接 compile 'com.github.Hitomis.transferee:Transferee:v1.1.0' 无法使用呀 提示Failed to resolve: com.github.Hitomis.transferee:Transferee:v1.1.0

**Comment by DRAWCORE** [comment]
> 用的是当前最新版本么？

请问现在需要使用您的库的话该怎么引用，直接直接 compile 'com.github.Hitomis.transferee:Transferee:v1.1.0' 无效。可否麻烦提供一下jar包，有个项目比较急。

**Comment by Yogurtla** [comment]
> > 用的是当前最新版本么？
> 
> 请问现在需要使用您的库的话该怎么引用，直接直接 compile 'com.github.Hitomis.transferee:Transferee:v1.1.0' 无效。可否麻烦提供一下jar包，有个项目比较急。



> > > 用的是当前最新版本么？
> > 
> > 
> > 是的，最新版本，com.github.Hitomis.transferee:Transferee:v1.1.0
> 
> 直接 compile 'com.github.Hitomis.transferee:Transferee:v1.1.0' 无法使用呀 提示Failed to resolve: com.github.Hitomis.transferee:Transferee:v1.1.0
我的是直接用的，如下
   compile 'com.github.Hitomis.transferee:Transferee:v1.1.0'
//图片查看：https://github.com/Hitomis/transferee

**Comment by DRAWCORE** [comment]
> > > 用的是当前最新版本么？
> > 
> > 
> > 请问现在需要使用您的库的话该怎么引用，直接直接 compile 'com.github.Hitomis.transferee:Transferee:v1.1.0' 无效。可否麻烦提供一下jar包，有个项目比较急。
> 
> > > > 用的是当前最新版本么？
> > > 
> > > 
> > > 是的，最新版本，com.github.Hitomis.transferee:Transferee:v1.1.0
> > 
> > 
> > 直接 compile 'com.github.Hitomis.transferee:Transferee:v1.1.0' 无法使用呀 提示Failed to resolve: com.github.Hitomis.transferee:Transferee:v1.1.0
> > 我的是直接用的，如下
> > compile 'com.github.Hitomis.transferee:Transferee:v1.1.0'
> > //图片查看：https://github.com/Hitomis/transferee

是不是还需要引入其它源，自带的google()和jcenter()找不到这个库

**Comment by Hitomis** [comment]
抱歉啊，v1.1.0  这个版本很早就不好用了，有一些bug和设计缺陷存在。新版版修复了这些问题。要使用的话直接下载当前最新的代码。然后以module 的形式引入。
