### ISSUE TITLE
建议不要基于Dialog

### ISSUE THREAD

**Issue by Pluckypan** [Hitomis/transferee#75]
1. 基于Dialog去显示ViewPager会存在Foucs变化的问题  那么在存在虚拟导航栏的手机上，从全屏状态下 调起Dialog会造成虚拟导航栏的闪烁
2. 如果要显示超巨图，基于目前的PhotoView根本行不通，Glide通过SimpleTaget的形式可以将原始图直接塞给PhotoView 但是会很卡 且最终会OOM。所以要么对PhotoView进行改造 支持区块加载，要不换图片显示组件。
**加油**

**Comment by Hitomis** [comment]
谢谢你这么详细建议
1.基于 Dialog 的原因是在项目初期我曾经尝试过很多方式的容器组件，Activity 和 Fragment 对于此项目来说太重，ViewGroup 很好，但是有更多的问题，例如很容易被其他 Level 更高的组件遮挡，最终权衡之下同时也是借鉴了国外一个项目选择 Dialog 。如果你有更好的容器组件推荐，请告诉我。谢谢。另外写这个项目的时候就拿很多带虚拟键盘的手机，例如htc ,三星，华为三大厂家的多款旗舰机跑过，并没有发现你说的虚拟导航栏闪烁问题。可能是我这边测试不全面，如果有准确的机型，请发给我准确的机型。我去测试一下。
2.针对 transferee 显示超巨图，确实是 transferee 的短板。曾经研究过高清图片显示组件SubsamplingScaleImageView。但是 SubsamplingScaleImageView 是自己继承 View 来重写图片的加载机制，并且使用 Bitmap 的形式绘制图片。由于使用 Bitmap 绘制图片显示，并且SubsamplingScaleImageView 功能非常专一，目前不知道如何做到从小图到全屏图片的过渡转变动画。这点很头疼。区块加载是个不错的提议。你能详细所以说么
