### ISSUE TITLE
BUG,克隆最新的代码,作为一个module

### ISSUE THREAD

**Issue by lydlovezjr** [Hitomis/transferee#76]
![qq 20181012181002](https://user-images.githubusercontent.com/19246347/46863699-a0793580-ce4a-11e8-86c9-350840c226cf.png)

**Comment by Hitomis** [comment]
给我看看你的使用 transferee 的代码

**Comment by lydlovezjr** [comment]
![qq 20181013103340](https://user-images.githubusercontent.com/19246347/46900359-761f8a80-ced3-11e8-9b4f-4ddcab8ba7ea.png)

**Comment by Hitomis** [comment]
@lydlovezjr 
config.setNowThumbnailIndex(position);
transferee.apply(config).show();

这两句代码调用了没？

**Comment by Hitomis** [comment]
你使用 transferee 的完整代码贴过来，你只贴了创建config 的代码。但是没看到你怎么使用这个config 的。很难帮到你。
