### ISSUE TITLE
这个支持自定义的 viewgroup 么

### ISSUE THREAD

**Issue by Wesley254619** [Hitomis/transferee#79]
看了使用方法的源码，必须要绑定一个 imageview 或是一个列表控件，但是我的图片展示是自定义的 viewgroup ，采用 new imageview 的方式来显示多张图片，这个库貌似就没法儿用了吧

**Comment by Wesley254619** [comment]
确实很强大，我自己改好了，支持自定义 viewgroup

**Comment by wsfbailebai** [comment]
> 确实很强大，我自己改好了，支持自定义 viewgroup

我也遇到这个问题，可以分享下不？

**Comment by Wesley254619** [comment]
> > 确实很强大，我自己改好了，支持自定义 viewgroup
> 
> 我也遇到这个问题，可以分享下不？

**Comment by Wesley254619** [comment]
> > 确实很强大，我自己改好了，支持自定义 viewgroup
> 
> 我也遇到这个问题，可以分享下不？

TransferConfig 中增加如下代码：
`private ViewGroup viewGroup;  `
`public ViewGroup getViewGroup() {
        return viewGroup;
    }`
`public void setViewGroup(ViewGroup viewGroup) {
        this.viewGroup = viewGroup;
    }`

TransferConfig.Builder 中增加如下代码：
`private ViewGroup viewGroup;`
`public TransferConfig bindViewGroup(ViewGroup viewGroup) {
            this.viewGroup = viewGroup;
            return create();
        }`

TransferConfig.create 中增加如下代码：
`config.setViewGroup(viewGroup);`

Transferee.fillOriginImages() 中增加如下代码：
`if (transConfig.getViewGroup() != null) {
            fillByViewGroup(originImageList);
        }`

`private void fillByViewGroup(final List<ImageView> originImageList) {
        ViewGroup viewGroup = transConfig.getViewGroup();
        int childCount = viewGroup.getChildCount();
        for (int i = 0; i < childCount; i++) {
            ImageView originImage = (ImageView) viewGroup.getChildAt(i);
            originImageList.add(originImage);
        }
        fillPlaceHolder(originImageList, childCount, 0, 0);
    }`
