### ISSUE TITLE
请问该库适用于瀑布流吗？RecyclerView瀑布流滑动滚出的imageView点击查看大图空指针？

### ISSUE THREAD

**Issue by Ximano** [Hitomis/transferee#87]
![image](https://user-images.githubusercontent.com/9362546/62853187-23467780-bd1e-11e9-9df9-464bff8a3c84.png)

**Comment by Ximano** [comment]
你好大佬，我在Transferee中相应的位置增加了StaggeredGridLayoutManager，但是暂不知如何获取正确的firstPos，lastPos。点击查看大图有时会在错误的position触发图片的放大动画展开大图。想到瀑布流中item是没有任何规则，只由源图片的尺寸去布局。所以想请问一下瀑布流是否可以用这种动画效果的浏览大图。请问大佬有什么好的处理方案？谢谢～
![image](https://user-images.githubusercontent.com/9362546/62908849-b7f7b680-bdac-11e9-8f42-b64abe403dd0.png)

**Comment by Hitomis** [comment]
请使用最新的代码编译，老版本已作废了
