### ISSUE TITLE
设置列表项的ImageView的scaleType="centerCrop",动画会有问题

### ISSUE THREAD

**Issue by longguowei** [Hitomis/transferee#9]
您好，如果设置列表项的ImageView的scaleType="centerCrop",动画会有问题，麻烦帮忙看看，谢谢

**Comment by Hitomis** [comment]
目前并不支持修改ScaleType ，这个问题目前也无法解决，如果您有好的思路，欢迎讨论哦

**Comment by Hitomis** [comment]
目前重构版本已经初步完成。您可以 pull 下来进行使用，如有问题请提 Issues
