### ISSUE TITLE
图片加载用的是universalimageloader？这个图片加载框架已经很小众了，能不能换成glide或者picaso?

### ISSUE THREAD

**Issue by scrylove** [Hitomis/transferee#93]
如题！！！！！！！！！！！！

**Comment by Hitomis** [comment]
[#88](https://github.com/Hitomis/transferee/issues/88)
transferee 核心并不是图片加载框架，目前只是内置了适合这个transferee的一套图片加载库，使用者可以随时替换，实现 imageLoader 接口即可。置于为什么内置的不是其他图片加载框架，可以看看 Readme 中的 1.2.0 更新日志
