### ISSUE TITLE
请教下，本项目是如何实现超长图显示的

### ISSUE THREAD

**Issue by zomll** [Hitomis/transferee#94]
测试发现本项目超长图也可以正常显示，代码里也没用使用BitmapRegionDecoder，据我所知，android 里的bitmap加载的图片长度是有一点限制的，为何本项目可以正常显示呢？

**Comment by Hitomis** [comment]
您好，transferee 基于处理后的图片进行展示，所以不需要使用BitmapRegionDecoder进行原图的区域分割处理展示。
transferee的焦点在于帮助需要快捷展示图片的功能，覆盖了绝大多数的需求。但是不适合去展示那些超级大图。毕竟这种功能需求的太少了，况且github上已经有太多这样的轮子去专门显示超大图。例如 BigImageViewer、subsampling-scale-image-view等等。 transferee 的侧重点和这些库不一样。

**Comment by zomll** [comment]
> 您好，transferee 基于处理后的图片进行展示，所以不需要使用BitmapRegionDecoder进行原图的区域分割处理展示。
> transferee的焦点在于帮助需要快捷展示图片的功能，覆盖了绝大多数的需求。但是不适合去展示那些超级大图。毕竟这种功能需求的太少了，况且github上已经有太多这样的轮子去专门显示超大图。例如 BigImageViewer、subsampling-scale-image-view等等。 transferee 的侧重点和这些库不一样。

多谢大佬百忙之中抽空回复，谢谢
