### ISSUE TITLE
老哥可不可以将截图外链，项目太大，下载失败

### ISSUE THREAD

**Issue by KunMinX** [Hitomis/transferee#96]
对这个项目很感兴趣，
两张截图共 30MB，目前卡在最后这两张图，一直下载失败。
所以可不可以外链呢，比如 sm.ms 这个网站。

相信许多网友都是通过 git clone --depth 1 去 clone 最后一次提交，所以一旦项目中两张图被移除 而改为外链，就能成功 clone。

**Comment by Hitomis** [comment]
sm.ms 上传的图片单张限制最大5M，没办法啊。我删除了一张图片，减小了十几M。
