### ISSUE TITLE
怎么可以改成支持视频

### ISSUE THREAD

**Issue by wangdongi** [Hitomis/transferee#99]

**Comment by Hitomis** [comment]
视频展开，其实是展开的视频中的某一帧作为封面的图像。究其根本还是图像的伸展过渡。在打开的之前获取这一帧图像（你的视频播放器首先得支持给我这一帧图像的功能），传递给 transferee。在伸展过渡动画执行完毕后，显示出视频播放器，让你的视频播放器播放视频。同样关闭也是同样的道理。
以上可知。对视频进行 操作。就是对视频某一帧图像进行伸缩过渡而已。
